### ISSUE TITLE
drop python 3.4 support, move to async/await syntax

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp-debugtoolbar#123]
(I mentioned this on #121 but I think it deserves it's own issue.)

I think aiohttp-debugtoolbar should drop support for python 3.4 and migrate to `async/await` syntax.

This should make further development quicker and easier.

I know aiohttp is continuing to support 3.4 but I really don think that means support packages have to do the same, for example aiohttp-devtools never supported 3.4 and no one has asked about it.

**Comment by doubledare704** [comment]
And we can add to docs a mention: if you need to use python 3.4 - look forward for using aiohttp < 2.0 and some specific version of debug_toolbar

**Comment by jettify** [comment]
I would like to drop 3.4, but aiohttp still support 3.4.

 @asvetlov @fafhrd91 what do you think about this?

**Comment by doubledare704** [comment]
You may fix current state in specific release version and migrate then to async/await.

**Comment by fafhrd91** [comment]
That's fine. We'll drop py3.4 support in 2018

**Comment by jettify** [comment]
ok, lets move to 3.5+ then

**Comment by samuelcolvin** [comment]
:+1: marvelous

**Comment by chrisimcevoy** [comment]
I started looking into this, but I admit I am a bit stuck on how to make [ContextSwitcher](https://github.com/aio-libs/aiohttp-debugtoolbar/blob/a1c3fb2b487bcaaf23eb71ee4c9c3cfc9cb94322/aiohttp_debugtoolbar/utils.py#L162-L211) work.

As far as I understand the implementation, it takes advantage of the old ```@asyncio.coroutine``` coroutine being iterable - which native ```async def``` coroutines aren't.

Any ideas how you might track context switches after migration to async/await...?
