### ISSUE TITLE
Add options for disable the check of host.

### ISSUE THREAD

**Issue by Arfey** [aio-libs/aiohttp-debugtoolbar#230]
When u use the docker container your resolve host inside container can changing after some time. So, i wanna be able to disable the check of host for display debugtoolbar for any host.

**Comment by Arfey** [comment]
https://github.com/aio-libs/aiohttp-debugtoolbar/pull/231

**Comment by msander** [comment]
This check should be separated from the exlude_prefixes option. Otherwise all requests to _debugtoolbar/* will appear in the list.
