### ISSUE TITLE
Slow to import

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp-debugtoolbar#394]
On my system, `import aiohttp_debugtoolbar` takes ~1.6s to run.

This seems excessive, and adds a noticeable amount of time to app reloading when developing with aiohttp-devtools.

**Comment by asvetlov** [comment]
I'm curious, why?
Did you try `python -X importtime ...` to analyze?

**Comment by Dreamsorcerer** [comment]
Not sure how to read `importtime` output, but viewing through `tuna` looks like this:
![Screenshot 2021-12-20 at 21-15-17 tuna - import log](https://user-images.githubusercontent.com/2203121/146833936-4311c4b3-8500-44d0-81f6-9cd1f65d3726.png)

If I'm reading that correctly, it looks like most of the time is probably spent with this packages code:
https://github.com/aio-libs/aiohttp-debugtoolbar/blob/master/aiohttp_debugtoolbar/panels/versions.py#L12-L33

A secondary issue is gunicorn getting imported via aiohttp.workers. Maybe it would be best to remove the gunicorn workers from `aiohttp/__init__.py` in v4? Just require users to import the workers directly if needed (same for anything else that's having a noticeable impact on the import time).

**Comment by asvetlov** [comment]
The main issue is `pkg_resources`, the famously slow package :)
I suggest replacing it with `importlib.metadata`.

Regarding gunicorn import -- yes. After upgrading the minimal required Python to 3.7 we can do `__getattr__` trick, similar to [`concurrent.futures`](https://github.com/python/cpython/blob/main/Lib/concurrent/futures/__init__.py).

If you can find time for both improvements -- you are welcome!
