### ISSUE TITLE
Conflicts with asyncio.gather()

### ISSUE THREAD

**Issue by vad** [aio-libs/aiohttp-debugtoolbar#41]
In one of my handlers I have the following line:

``` py
await asyncio.gather(*tasks)
```

I use the `gather()` function to propagate exceptions (instead of `asyncio.wait` that would only collect them). With the debug toolbar installed, exceptions are not propagated anymore from the task to the handler. If an exception happens in one of the tasks I get a white 500 page.

I guess that the debug toolbar installs an exception handler and that breaks the gathering of exceptions.

**Comment by jettify** [comment]
Hi, could you please provide simple snippet to reproduce this behaviour so I can play with it locally?

**Comment by vad** [comment]
Ehm... I'm not able to replicate in a snippet, that only happens in the project... But writing the snipped I've noticed another thing. The snippet is the following:

```py
import asyncio

import aiohttp_debugtoolbar
from aiohttp import web
from aiohttp.web_reqrep import json_response


async def raise_exc():
    raise Exception('raise!')

async def handler(request, *args):
    tasks = [
        asyncio.ensure_future(raise_exc()),
    ]
    await asyncio.gather(*tasks)
    return json_response({})


if __name__ == "__main__":

    # loop = asyncio.get_event_loop()
    # loop.set_debug(True)

    app = web.Application()
    aiohttp_debugtoolbar.setup(app)

    app.router.add_route('GET', '/', handler)

    web.run_app(app, port=13323)
```

If I uncomment `loop.set_debug(True)`, with the debug toolbar I get:

```
TypeError: throw() takes 2 positional arguments but 4 were given
```

In my project the behaviour is different (as described above) but the thing is the same: I can have `loop.set_debug(True)` OR the debug toolbar, not both.

Personally I don't even know what `loop.set_debug(True)` is for (ok, i've read the doc but i don't really understand), maybe you can simply document this issue?

**Comment by asvetlov** [comment]
Fixed by aiohttp I believe
