### ISSUE TITLE
Current release doesn't support 3.11

### ISSUE THREAD

**Issue by arcan1s** [aio-libs/aiohttp-debugtoolbar#477]
The latest release 0.6.0 contains some unmerged changes, e.g. https://github.com/aio-libs/aiohttp-debugtoolbar/pull/317. Starting from python 3.11 global inline flags can only be set at the start of the expression, see https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11

**Comment by Dreamsorcerer** [comment]
I think you mean there are changes that have not been released yet.

debugtoolbar is on my list to revive and get a new release out.

**Comment by arcan1s** [comment]
yeah, thank you, will wait for updates then :+1:

**Comment by arcan1s** [comment]
thank you!
